development:
  site_path: authorizartion_server_site_path # https://abc.com
  redirect_uri: your_redirect_uri
  client_id: your_client_id
  client_secret : your_client_secret

test:
  site_path: authorizartion_server_site_path # https://abc.com
  redirect_uri: your_redirect_uri
  client_id: your_client_id
  client_secret : your_client_secret
